/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 51;
  /** RegularExpression Id. */
  int STRING = 52;
  /** RegularExpression Id. */
  int ID = 53;
  /** RegularExpression Id. */
  int LETTER = 54;
  /** RegularExpression Id. */
  int DIGIT = 55;
  /** RegularExpression Id. */
  int UNDER = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"true\"",
    "\"false\"",
    "\"new\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"extends\"",
    "\"synchronized\"",
    "\"return\"",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "\".\"",
    "\"=\"",
    "\"!\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"<\"",
    "\"&&\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"main\"",
    "\"String\"",
    "\"Thread\"",
    "\"Xinu\"",
    "\"this\"",
    "\"null\"",
    "<INT>",
    "<STRING>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"_\"",
    "<token of kind 57>",
  };

}
